# Generated by Django 3.1.4 on 2021-01-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=150)),
                ('coordinates', models.CharField(max_length=100)),
                ('social_media', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pois', models.ManyToManyField(through='poi.Layer', to='poi.Poi')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='poi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.poi'),
        ),
        migrations.AddField(
            model_name='layer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.tag'),
        ),
    ]
