# Generated by Django 3.1.7 on 2021-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='tags',
            field=models.ManyToManyField(through='poi.Layer', to='poi.Tag'),
        ),
    ]
