# Generated by Django 3.1.4 on 2021-01-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_auto_20210104_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.poi')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='pois',
            field=models.ManyToManyField(through='poi.Layer', to='poi.Poi'),
        ),
        migrations.RemoveField(
            model_name='poi',
            name='tags',
        ),
        migrations.AddField(
            model_name='poi',
            name='tags',
            field=models.ManyToManyField(through='poi.Layer', to='poi.Tag'),
        ),
    ]
